import Image from 'next/image';

export default function SkillList() {
	return (
		<div className="flex flex-col">
			<div className="text-2xl font-semibold pb-4">Skills 💪</div>
			<div className="flex flex-wrap gap-2">
				<Image
					priority
					src="https://img.shields.io/badge/HTML5-E34F26?style=flat-square&logo=HTML5&logoColor=white"
					width={120}
					height={40}
					alt=""
				/>
				<Image
					priority
					src="https://img.shields.io/badge/CSS3-1572B6?style=flat-square&logo=CSS3&logoColor=white"
					width={120}
					height={40}
					alt=""
				/>
				<Image
					priority
					src="https://img.shields.io/badge/JavaScript-F7DF1E?style=flat-square&logo=JavaScript&logoColor=white"
					width={160}
					height={40}
					alt=""
				/>
				<Image
					priority
					src="https://img.shields.io/badge/TypeScript-3178C6?style=flat-square&logo=TypeScript&logoColor=white"
					width={160}
					height={40}
					alt=""
				/>
				<Image
					priority
					src="https://img.shields.io/badge/React-222?style=flat-square&logo=React&logoColor=61DAFB"
					width={120}
					height={40}
					alt=""
				/>
				<Image
					priority
					src="https://img.shields.io/badge/React Native-222?style=flat-square&logo=React&logoColor=61DAFB"
					width={180}
					height={40}
					alt=""
				/>
				<Image
					priority
					src="https://img.shields.io/badge/React PWA-222?style=flat-square&logo=React&logoColor=61DAFB"
					width={170}
					height={40}
					alt=""
				/>
				<Image
					priority
					src="https://img.shields.io/badge/Redux-764ABC?style=flat-square&logo=redux&logoColor=white"
					width={120}
					height={40}
					alt=""
				/>
				<Image
					priority
					src="https://img.shields.io/badge/Recoil-3578E5?style=flat-square&logo=recoil&logoColor=white"
					width={120}
					height={40}
					alt=""
				/>
				<Image
					priority
					src="https://img.shields.io/badge/Next.js-000?style=flat-square&logo=next.js&logoColor=white"
					width={150}
					height={40}
					alt=""
				/>
				<Image
					priority
					src="https://img.shields.io/badge/Node.js-339933?style=flat-square&logo=Node.js&logoColor=white"
					width={150}
					height={40}
					alt=""
				/>
				<Image
					priority
					src="https://img.shields.io/badge/Express-00AAE7?style=flat-square&logo=express&logoColor=white"
					width={150}
					height={40}
					alt=""
				/>
				<Image
					priority
					src="https://img.shields.io/badge/NPM-CB3837?style=flat-square&logo=npm&logoColor=white"
					width={110}
					height={40}
					alt=""
				/>
				<Image
					priority
					src="https://img.shields.io/badge/PM2-2B037A?style=flat-square&logo=pm2&logoColor=white"
					width={110}
					height={40}
					alt=""
				/>
				<Image
					priority
					src="https://img.shields.io/badge/Aws Amplify-ff9900?style=flat-square&logo=awsamplify&logoColor=white"
					width={160}
					height={40}
					alt=""
				/>
				<Image
					priority
					src="https://img.shields.io/badge/Aws S3-569A31?style=flat-square&logo=amazons3&logoColor=white"
					width={120}
					height={40}
					alt=""
				/>
				<Image
					priority
					src="https://img.shields.io/badge/Aws Cognito-FF9900?style=flat-square&logo=amazonaws&logoColor=white"
					width={160}
					height={40}
					alt=""
				/>
				<Image
					priority
					src="https://img.shields.io/badge/Git-f05032?style=flat-square&logo=Git&logoColor=white"
					width={90}
					height={40}
					alt=""
				/>
				<Image
					priority
					src="https://img.shields.io/badge/Netlify-00C7B7?style=flat-square&logo=netlify&logoColor=white"
					width={140}
					height={40}
					alt=""
				/>
				<Image
					priority
					src="https://img.shields.io/badge/Vercel-000000?style=flat-square&logo=vercel&logoColor=white"
					width={120}
					height={40}
					alt=""
				/>
			</div>
			<div className="text-2xl font-semibold pb-4 pt-8">Designs 🎨</div>
			<div className="flex flex-wrap gap-2">
				<Image
					priority
					src="https://img.shields.io/badge/MUI-007FFF?style=flat-square&logo=mui&logoColor=white"
					width={120}
					height={40}
					alt=""
				/>
				<Image
					priority
					src="https://img.shields.io/badge/Bootstrap-7952b3?style=flat-square&logo=bootstrap&logoColor=white"
					width={150}
					height={40}
					alt=""
				/>
				<Image
					priority
					src="https://img.shields.io/badge/Styled Components-DB7093?style=flat-square&logo=styledcomponents&logoColor=white"
					width={200}
					height={40}
					alt=""
				/>
				<Image
					priority
					src="https://img.shields.io/badge/Tailwned CSS-06B6D4?style=flat-square&logo=Tailwned CSS&logoColor=white"
					width={140}
					height={40}
					alt=""
				/>
				<Image
					priority
					src="https://img.shields.io/badge/Zeplin-F0D722?style=flat-square&logo=Zeplin&logoColor=white"
					width={100}
					height={40}
					alt=""
				/>
				<Image
					priority
					src="https://img.shields.io/badge/Figma-f24e1e?style=flat-square&logo=figma&logoColor=white"
					width={120}
					height={40}
					alt=""
				/>
			</div>
			<div className="text-2xl font-semibold pb-4 pt-8">Storages 📂</div>
			<div className="flex flex-wrap gap-2">
				<Image
					priority
					src="https://img.shields.io/badge/PostgreSQL-4169E1?style=flat-square&logo=PostgreSQL&logoColor=white"
					width={160}
					height={40}
					alt=""
				/>
				<Image
					priority
					src="https://img.shields.io/badge/Redis-dc382d?style=flat-square&logo=Redis&logoColor=white"
					width={120}
					height={40}
					alt=""
				/>
				<Image
					priority
					src="https://img.shields.io/badge/Amazon S3-569a31?style=flat-square&logo=amazons3&logoColor=white"
					width={140}
					height={40}
					alt=""
				/>
				<Image
					priority
					src="https://img.shields.io/badge/Amazon DynamoDB-4053d6?style=flat-square&logo=amazondynamodb&logoColor=white"
					width={200}
					height={40}
					alt=""
				/>
			</div>
			<div className="text-2xl font-semibold pb-4 pt-8">Tried it 👊</div>
			<div className="flex flex-wrap gap-2">
				<Image
					priority
					src="https://img.shields.io/badge/Firebase-FFCA28?style=flat-square&logo=firebase&logoColor=white"
					width={160}
					height={40}
					alt=""
				/>
				<Image
					priority
					src="https://img.shields.io/badge/Amazon EC2-FF9900?style=flat-square&logo=amazonec2&logoColor=white"
					width={180}
					height={40}
					alt=""
				/>
				<Image
					priority
					src="https://img.shields.io/badge/Spring-6DB33F?style=flat-square&logo=spring&logoColor=white"
					width={140}
					height={40}
					alt=""
				/>
				<Image
					priority
					src="https://img.shields.io/badge/InfluxDB-22ADF6?style=flat-square&logo=influxdb&logoColor=white"
					width={140}
					height={40}
					alt=""
				/>
			</div>
		</div>
	);
}
