export const introduceData = {
	name: '유권희',
	title: '꾸준히 성장하는 개발자',
	subtitle: '안녕하세요! 꾸준히 성장하는 프론트엔드 개발자 유권희 입니다,',
	introduceList: [
		'도전적인 목표를 통해, 습득하고 배우는 과정을 즐깁니다.',
		'개발자의 편한 개발보다 사용자의 편의를 더 중요하게 생각합니다.',
		'한 번 시작한 일은 끝까지 완수를 해야 하는 성격 탓에 엉덩이 무겁다는 말을 많이 듣습니다.',
	],

	birthday: '1997. 01. 12',
	residence: '경기도 성남시',
	email: 'yoogwonhee@naver.com',
	university: '충남대학교 컴퓨터공학과',
	phone: '010-7209-5036',
};

export const projectData: any = {
	interminds_storepop: {
		name: '(인터마인즈) 신규 무인매장 관리자 웹',
		skills: {
			Front: [
				'TypeScript',
				'React',
				'Nextjs',
				'Recoil',
				'Mui',
				'Tailwind CSS',
				'AWS Amplify',
				'AWS Cognito',
			],
			Storage: ['AWS S3'],
		},
		details: [
			'무인매장 점주 및 인터마인즈 직원이 무인매장을 관리 할 수 있는 웹 개발',
		],
		works: [
			'지점 등록 / 상태조회 , 진열도 등록 , 상품 등록',
			'회원 관리 기능',
			'판매 관리',
			'환불 및 재결제',
			'매장 CCTV 영상 확인 기능',
			'운영 및 배포',
		],
		participants: { 기획자: 1, 프론트엔드: 1, 백엔드: 2 },
		period: '2023/12/28 ~ 진행중',
		scope: '프론트엔드',
		imgCount: 8,
	},
	interminds_pwa: {
		name: '(인터마인즈) 무인매장 결제 PWA',
		skills: {
			Front: ['Javascript', 'React', 'Recoil', 'Figma'],
			Storage: ['AWS S3'],
		},
		works: [
			'로그인 및 회원가입 ( 카카오로그인 및 자체로그인 )',
			'결제 api 연동',
			'적립금 / 쿠폰 관리 기능',
			'구매내역',
			'운영 및 배포',
		],
		details: [
			'결제 QR을 사용하여 무인매장 결제를 하고 적립금 및 쿠폰을 관리할 수 있는 앱 개발',
		],
		participants: { 기획자: 1, 프론트엔드: 1, 백엔드: 1, 디자이너: 1 },
		scope: '프론트엔드',
		period: '2023/11/20 ~ 2024/03/04',
		imgCount: 11,
	},
	interminds_admin: {
		name: '(인터마인즈) 관리자웹',
		skills: {
			Front: [
				'Javascript',
				'React',
				'Redux',
				'Bootstrap',
				'AWS Amplify',
				'AWS Cognito',
			],
			Back: [
				'Node.js',
				'Express',
				'PM2',
				'Github Action',
				'AWS CodeDeploy',
				'AWS EC2',
				'AWS S3',
			],
			Storage: ['AWS S3', 'PostgreSQL', 'Redis', 'InfluxDB'],
		},
		works: [
			'회원관리 - 가입 / 로그인 / 정보수정',
			'지점 등록 , 진열도 등록 , 상품 등록',
			'지점 상태 조회',
			'판매 관리',
			'환불 및 재결제',
			'Object Detection 관련 세팅 기능',
			'운영 및 배포',
		],
		details: [
			'관리자 및 점주 관리 웹 개발',
			'편의성 개선 (필터 세분화, 표현 다양화)',
			'속도 개선 (가상화 렌더링)',
		],
		participants: { 기획자: 1, 프론트엔드: 2, 백엔드: 3 },
		scope: '프론트엔드 및 백엔드',
		period: '2023/02/22 ~ 2024/01/30',
		imgCount: 3,
		url: 'https://www.interminds-admin.com/',
	},
	interminds_cs: {
		name: '(인터마인즈) CS 관리 웹',
		skills: {
			Front: [
				'Javascript',
				'React',
				'Redux',
				'Bootstrap',
				'AWS Amplify',
				'AWS Cognito',
			],
			Back: [
				'Node.js',
				'Express',
				'PM2',
				'Github Action',
				'AWS CodeDeploy',
				'AWS EC2',
				'AWS S3',
			],
			Storage: ['AWS S3', 'PostgreSQL', 'Redis'],
		},
		works: [
			'이슈 통계',
			'이슈 등록 및 수정',
			'스토어 정보 등록 및 수정',
			'서버개발',
			'코드 자동 배포',
			'운영 및 배포',
		],
		details: ['CS 관리 웹 개발'],
		participants: { 기획자: 1, 웹개발자: 1 },
		scope: '프론트엔드 및 백엔드',
		period: '2023/01/16 ~ 2023/04/19',
		imgCount: 2,
		url: 'https://cs.interminds-admin.com/',
	},
	psdl_web: {
		name: '(피에스디엘) 오늘은 더치페이 사장님 웹',
		skills: {
			Front: [
				'Javascript',
				'React-native',
				'Redux',
				'Bootstrap',
				'AWS Amplify',
			],
			Storage: ['AWS DynamoDB'],
		},
		works: [
			'회원관리 - 가입 / 로그인 / 정보수정',
			'가게 정보 등록 및 수정',
			'메뉴 등록 및 수정',
			'옵션 등록 및 수정',
			'매출 관리 조회',
			'반응형 추가',
		],
		details: ['사장님 전용 웹 사이트'],
		participants: { 기획자: 1, 프론트엔드: 2, 백엔드: 1, 디자이너: 1 },
		scope: '프론트엔드',
		period: '2022/05/02 ~ 2022/08/12',
		imgCount: 1,
	},
	psdl_tablet: {
		name: '(피에스디엘) 오늘은 더치페이 Tablet 앱',
		skills: {
			Front: [
				'Javascript',
				'React-native',
				'Redux',
				'Bootstrap',
				'AWS IoT Core',
			],
			Storage: ['AWS DynamoDB'],
		},
		works: [
			'로그인',
			'MQTT를 통해 주문 내용 접수',
			'현재 주문 상태 제공 및 변경',
			'가게 정보 및 매출 내역 제공',
		],
		details: ['주문 정보를 보여주는 테블릿 전용 앱 개발'],
		participants: { 기획자: 1, 프론트엔드: 2, 백엔드: 1, 디자이너: 1 },
		scope: '프론트엔드',
		period: '2022/05/02 ~ 2022/08/12',
		imgCount: 3,
	},
	psdl_app: {
		name: '(피에스디엘) 오늘은 더치페이 앱',
		skills: {
			Front: [
				'Javascript',
				'React-native',
				'Redux',
				'Bootstrap',
				'AWS IoT Core',
			],
			Storage: ['AWS DynamoDB'],
		},
		works: [
			'회원관리 - 가입 / 로그인 / 정보수정',
			'NFC 및 QR로 매장 정보 읽는 기능',
			'메뉴 주문 / 옵션 선택 기능',
			'결제 / 더치페이 (MQTT 를 통해 더치페이 다른 사용자에게 정보 전송)',
			'결제 내역 확인',
			'DB 구조 설계',
		],
		details: [
			'매장 테이블의 NFC정보를 읽고 메뉴를 주문 및 결제, 더치페이 앱',
		],
		participants: { 기획자: 1, 프론트엔드: 2, 백엔드: 1, 디자이너: 1 },
		scope: '프론트엔드',
		period: '2022/05/02 ~ 2022/08/12',
		imgCount: 6,
	},
	bhaptics_login: {
		name: '(비햅틱스) 통합로그인 웹페이지',
		skills: {
			Front: [
				'TypeScript',
				'React',
				'HTML',
				'CSS',
				'Tailwind CSS',
				'Zeplin',
			],
		},
		works: [
			'회원관리 - 유저 타입 별 가입 / 로그인 / 정보수정',
			'디자인안에 맞게 UI 제작 ( Zeplin을 통해 디자이너와 소통 )',
			'모바일화면에서도 사용자가 잘 사용할 수 있도록 반응형 추가',
		],
		details: [
			'기존에 두개인 웹사이트를 하나의 페이지에서 회원가입 및 로그인하여 사용할 수 있도록 웹페이지 추가',
		],
		participants: { 기획자: 1, 프론트엔드: 1, 디자이너: 1 },
		scope: '프론트엔드',
		period: '2021/10/04 ~ 2021/10/22',
		imgCount: 3,
		url: 'https://login.bhaptics.com/',
	},
	bhaptics_app: {
		name: '(비햅틱스) 비햅틱스 플레이어',
		skills: {
			Front: [
				'TypeScript',
				'React-native',
				'Redux',
				'Tailwind CSS',
				'Zeplin',
			],
			Back: ['Firebase'],
			Storage: ['Firebase Realtime Database'],
		},
		works: [
			'회원관리 - 유저 타입 별 가입 / 로그인 / 정보수정',
			'테마변경 - 선택한 테마에 따라 앱 전체 색 변경',
			'코드 리팩토링 - 코드를 깔끔하게 수정',
			'이벤트 섹션 추가 - 이벤트 기획 및 개발',
			'커뮤니티 섹션 추가 - 업로드 / 댓글 / 좋아요 / 신고 / 검색 기능',
			'앱 ui개선 ( Zeplin을 통해 디자이너와 소통 )',
		],
		details: [
			'비햅틱스 플레이어 ( 소리를 햅틱으로 변환시켜주는 장비 )를 조작할 수 있는 앱 유지보수',
		],
		participants: { 기획자: 1, 앱개발자: 3, 디자이너: 2 },
		scope: '프론트엔드 및 백엔드',
		period: '2021/08/16 ~ 2021/12/17',
		imgCount: 2,
	},
	secondGround: {
		name: '(세컨그라운드) 물품 관리 페이지',
		skills: {
			Front: ['Java', 'HTML', 'CSS'],
			Back: ['Spring'],
			Storage: ['H2'],
		},
		works: ['물품 현재 상태를 보여줌', '물품 추가 / 삭제 / 상태변경 기능'],
		details: ['회사 관리자 계정에 한에 물품 관리 페이지 제작'],
		participants: { 본인: 1 },
		scope: '프론트엔드 및 백엔드',
		period: '2021/01/04 ~ 2021/02/12',
		imgCount: 1,
	},
	animal: {
		name: '동물상테스트',
		skills: {
			Front: ['HTML', 'CSS', 'Machine Learning', 'Crawling'],
		},
		works: [
			'크롤링을 사용하여 동물상 별 연예인 이미지 수집',
			'이미지 학습 모델 구현',
			'웹 페이지 UI 구현',
			'모바일화면에서도 사용자가 잘 사용할 수 있도록 반응형 추가',
			'공유 기능 및 댓글 기능 추가',
		],
		details: ['머신러닝 기술을 활용하여 동물상 판별 웹 개발'],
		participants: { 본인: 1 },
		scope: '프로젝트 전체',
		period: '2021/07/28 → 2021/07/30',
		imgCount: 2,
	},
	portfolio: {
		name: '포트폴리오',
		skills: {
			Front: [
				'TypeScript',
				'React',
				'Next.js',
				'Tailwind CSS',
				'Material UI',
				'Vercel',
			],
		},

		details: [
			'포트폴리오 페이지 개발',
			'간단한 자기소개, Github 및 기술블로그 소개, 기술 스택, 프로젝트 경험, 엄무 경력',
			'Vercel을 이용하여 정적 웹사이트를 배포',
		],
		participants: { 본인: 1 },
		scope: '프로젝트 전체',
		period: '2024/03/14 ~ 진행중',
		imgCount: 1,
	},
};

export const workData = [
	{
		company: '인터마인즈',
		department: 'sw그룹',
		position: '연구원',
		period: '22.08 ~ 재직중',
		skills: [
			'React',
			'ReactPWA',
			'Nextjs',
			'JavaScript',
			'TypeScript',
			'TypeScript',
			'AWS Amplify',
			'AWS Cognito',
			'AWS S3',
			'Nodejs',
			'Express',
			'PostgreSQL',
			'Redis',
			'InfluxDB',
		],
	},
	{
		company: '피에스디엘',
		department: 'sw개발팀',
		position: '연구원',
		period: '22.04 ~ 22.08',
		skills: [
			'React',
			'React-native',
			'TypeScript',
			'AWS Amplify',
			'AWS Cognito',
			'AWS DynamoDB',
			'AWS S3',
		],
	},
	{
		company: '비햅틱스',
		department: 'sw개발팀',
		position: '인턴',
		period: '21.08 ~ 21.12',
		skills: ['React', 'React-native', 'TypeScript', 'Firebase'],
	},
	{
		company: '세컨그라운드',
		department: '개발팀',
		position: '인턴',
		period: '20.12 ~ 21.02',
		skills: ['Spring framework', 'Java', 'Html', 'Css'],
	},
];
